apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-hello-world-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/medhat-ramadan/nodejs-hello-world.git
