---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:   
  name: jazz-cash-dev-user

spec:
  passwordSecretKeyRef:    
    name: jazzcash-mongo-admin-secret    
    # Match to metadata.name of the User Secret
    key: password
  username: "dev"

  db: "admin" 
  mongodbResourceRef:
    name: "jazzcash"
    # Match to MongoDB resource using authenticaiton
  roles:
    - db: "admin"
      name: "clusterAdmin"
    - db: "admin"
      name: "userAdminAnyDatabase"
    - db: "admin"
      name: "readWrite"
    - db: "admin"
      name: "userAdminAnyDatabase"
...
