apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: jazzcash
  namespace: mongodb
spec:
  members: 3
  version: 4.2.7
  type: ReplicaSet
  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: om-medhat-credentials
  security:
    authentication:
      enabled : true
      modes: ["SCRAM"]
